### ISSUE TITLE
Timestamps without time zone information

### ISSUE THREAD

**Issue by klokare** [wpsinc/api-documentation-jekyll#1]
Not sure if this is a tip to be added to the documentation or a issue to be submitted about the API. The timestamps for created_at and updated_at only contain the date and time (no milliseconds, though). This means that the user must assume a time zone if parsing into a Time object. For example, in Go:

```go
// Example data from actual JSON response
updatedAt := "2016-06-17 20:50:52"

// ignoring errors for the example
loc, _ := time.LoadLocation("America/Denver") // returns Mountain Time, assumed as WPS is in Boise
t, _ := time.ParseInLocation("2006-01-02 15:04:05", updatedAt, loc)
```

So the tip would be to parse the timestamp in the correct time zone otherwise you might end up with the wrong time and, possibly, date if your code is running in a different location than the WPS servers.

**Comment by AustinMaddox** [comment]
Added Timezone explanation to the bottom of the FAQ page in 5442ea2ba790102db76af76924dcc071774fa0e4.

Comments, questions, concerns, and feedback can be addressed to web_services@wps-inc.com. Thanks!
